#!/usr/bin/env python3
import requests
import argparse
import sys
import loader
from display import display

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Process information about corona cases')

    parser.add_argument('--plotly', help='use plotly', action='store_true')

    parser.add_argument('source', help='some supported two-letter country like "cz" or "sk"')

    args = parser.parse_args()

    data = loader.load_data(args)
    display(data, args)
    sys.exit(0)
